=== zhiwi1/task2epam/src/main/resources/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/flowers"
        xmlns:tns="http://www.example.org/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element name="time-flower" type="tns:time-flower" minOccurs="16" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="flower">
        <sequence>
            <element name="name" type="tns:name-flower"/>
            <element ref="tns:soil"/>
            <element ref="tns:visual-parameters"/>
            <element ref="tns:growing-tips"/>
            <element ref="tns:multiplying"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="origin" use="optional" default="Unknown">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Belarus"/>
                    <enumeration value="China"/>
                    <enumeration value="America"/>
                    <enumeration value="Russia"/>
                    <enumeration value="Iran"/>
                    <enumeration value="Tunis"/>
                    <enumeration value="Greece"/>
                    <enumeration value="Unknown"/>
                </restriction>
            </simpleType>
        </attribute>

    </complexType>
    <complexType name="time-flower">
        <complexContent>
            <extension base="tns:flower">
                <sequence>
                    <element name="transfer-time" type="dateTime"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="soil">
        <simpleType>
            <restriction base="string">
                <enumeration value="podzol"/>
                <enumeration value="unpaved"/>
                <enumeration value="sodpodzol"/>
            </restriction>
        </simpleType>
    </element>
    <element name="visual-parameters">
        <complexType>
            <sequence>
                <element name="stem-color" type="string"/>
                <element name="leaf-color" type="string"/>
                <element name="average-size" type="positiveInteger"/>
            </sequence>
        </complexType>
    </element>

    <element name="growing-tips">
        <complexType>
            <sequence>
                <element ref="tns:temperature"/>
                <element name="lightning" type="boolean"/>
                <element name="watering" type="positiveInteger"/>
            </sequence>
        </complexType>
    </element>
    <element name="temperature">
        <simpleType>
            <restriction base="integer">
                <minInclusive value="-273"/>
                <maxInclusive value="100"/>
            </restriction>
        </simpleType>
    </element>
    <element name="multiplying">
        <simpleType>
            <restriction base="string">
                <enumeration value="seed"/>
                <enumeration value="stalk"/>
                <enumeration value="liaf"/>
            </restriction>
        </simpleType>
    </element>
    <simpleType name="name-flower">
        <restriction base="string">
            <pattern value="([A-Z]|[a-z])+"/>
        </restriction>
    </simpleType>
    <element name="flower" type="tns:flower" abstract="true"/>
    <element name="time-flower" type="tns:time-flower" substitutionGroup="tns:flower"/>

</schema>

=== zhiwi1/task2epam/src/test/resources/data/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/flowers"
        xsi:schemaLocation="http://www.example.org/flowers flowers.xsd">
    <time-flower id="flw1" origin="China" >
        <name>rose</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>light-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>60</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <lightning>true</lightning>
            <watering>1400</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <transfer-time>2002-05-30T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw2" origin="Iran" >
        <name>tulip</name>
        <soil>podzol</soil>
        <visual-parameters>
            <stem-color>medium-green</stem-color>
            <leaf-color>medium-green</leaf-color>
            <average-size>30</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <lightning>true</lightning>
            <watering>1200</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2002-05-30T09:00:09</transfer-time>
    </time-flower>
    <time-flower id="flw3" origin="Russia" >
        <name>sunflower</name>
        <soil>podzol</soil>
        <visual-parameters>
            <stem-color>medium-green</stem-color>
            <leaf-color>medium-green</leaf-color>
            <average-size>100</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <lightning>true</lightning>
            <watering>600</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2019-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw4" origin="Belarus" >
        <name>cornflower</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>medium-green</leaf-color>
            <average-size>70</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>21</temperature>
            <lightning>true</lightning>
            <watering>500</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2019-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw5" origin="Greece" >
        <name>violet</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>5</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>24</temperature>
            <lightning>true</lightning>
            <watering>600</watering>
        </growing-tips>
        <multiplying>liaf</multiplying>
        <transfer-time>2019-03-10T09:00:20</transfer-time>
    </time-flower>
    <time-flower id="flw6" origin="Tunis" >
        <name>carnation</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>50</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <lightning>true</lightning>
            <watering>500</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <transfer-time>2019-03-10T09:00:21</transfer-time>
    </time-flower>
    <time-flower id="flw7" origin="America" >
        <name>spathiphyllum</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>medium-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>30</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>23</temperature>
            <lightning>false</lightning>
            <watering>1200</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <transfer-time>2020-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw8" origin="China" >
        <name>aster</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>40</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <lightning>true</lightning>
            <watering>1500</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2021-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw9" origin="Belarus" >
        <name>maylily</name>
        <soil>podzol</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>10</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>21</temperature>
            <lightning>false</lightning>
            <watering>800</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2021-03-15T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw10" origin="Belarus" >
        <name>snowdrop</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>medium-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>10</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <lightning>false</lightning>
            <watering>1200</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2021-03-20T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw11" origin="Belarus" >
        <name>chamomile</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>medium-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>10</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>23</temperature>
            <lightning>true</lightning>
            <watering>900</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2021-03-10T10:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw12" origin="Russia" >
        <name>lotus</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>300</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <lightning>false</lightning>
            <watering>10000</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2021-04-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw13" origin="America" >
        <name>pansy</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>5</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>23</temperature>
            <lightning>true</lightning>
            <watering>800</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2022-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw14" origin="America" >
        <name>orchid</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>light-green</stem-color>
            <leaf-color>medium-green</leaf-color>
            <average-size>10</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <lightning>true</lightning>
            <watering>100</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2021-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw15" origin="Belarus" >
        <name>gladiolus</name>
        <soil>podzol</soil>
        <visual-parameters>
            <stem-color>light-green</stem-color>
            <leaf-color>light-green</leaf-color>
            <average-size>40</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>24</temperature>
            <lightning>true</lightning>
            <watering>1000</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
        <transfer-time>2024-03-10T09:00:00</transfer-time>
    </time-flower>
    <time-flower id="flw16" origin="Belarus" >
        <name>lavender</name>
        <soil>sodpodzol</soil>
        <visual-parameters>
            <stem-color>dark-green</stem-color>
            <leaf-color>dark-green</leaf-color>
            <average-size>80</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <lightning>true</lightning>
            <watering>1900</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <transfer-time>2021-03-10T09:00:01</transfer-time>
    </time-flower>
</flowers>
